exceptions_arr = {
    'ValueError': 'Введены данные некорректного типа',
    'WrongLimitsArgument': 'Введенные данные не соответсвуют ни одному пункту',
    'FileNotFound': 'Файл с таким именем не найден',
    'TooMuchLimits': 'Введено больше 2 чисел для задания начального приближения',
    'BiggerLeftLimit': 'Левая граница для начального приближения больше правой',
    'NegativeAccuracy': 'Отрицательная погрешность вычислений',
    'RepeatingEquationsNumbers': 'Выбраны повторяющиеся номера уравнений'
}